// <auto-generated />
using System;
using IPL.ECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPL.ECommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260822061456_AddOrders")]
    partial class AddOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Franchises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CSK",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/csk.png",
                            Name = "Chennai Super Kings"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MI",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/mi.png",
                            Name = "Mumbai Indians"
                        },
                        new
                        {
                            Id = 3,
                            Code = "RCB",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/rcb.png",
                            Name = "Royal Challengers Bengaluru"
                        },
                        new
                        {
                            Id = 4,
                            Code = "KKR",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/kkr.png",
                            Name = "Kolkata Knight Riders"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SRH",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/srh.png",
                            Name = "Sunrisers Hyderabad"
                        },
                        new
                        {
                            Id = 6,
                            Code = "RR",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/rr.png",
                            Name = "Rajasthan Royals"
                        },
                        new
                        {
                            Id = 7,
                            Code = "DC",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/dc.png",
                            Name = "Delhi Capitals"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PBKS",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/pbks.png",
                            Name = "Punjab Kings"
                        },
                        new
                        {
                            Id = 9,
                            Code = "GT",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/gt.png",
                            Name = "Gujarat Titans"
                        },
                        new
                        {
                            Id = 10,
                            Code = "LSG",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LogoUrl = "/images/franchises/lsg.png",
                            Name = "Lucknow Super Giants"
                        });
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductType");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official Chennai Super Kings jersey.",
                            FranchiseId = 1,
                            ImageUrl = "/images/products/csk-jersey.png",
                            IsActive = true,
                            Name = "CSK Official Jersey",
                            Price = 2999.00m,
                            ProductType = 1,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official Chennai Super Kings cap.",
                            FranchiseId = 1,
                            ImageUrl = "/images/products/csk-cap.png",
                            IsActive = true,
                            Name = "CSK Official Cap",
                            Price = 999.00m,
                            ProductType = 2,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chennai Super Kings supporter flag.",
                            FranchiseId = 1,
                            ImageUrl = "/images/products/csk-flag.png",
                            IsActive = true,
                            Name = "CSK Supporter Flag",
                            Price = 499.00m,
                            ProductType = 3,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official Mumbai Indians jersey.",
                            FranchiseId = 2,
                            ImageUrl = "/images/products/mi-jersey.png",
                            IsActive = true,
                            Name = "MI Official Jersey",
                            Price = 2999.00m,
                            ProductType = 1,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official Mumbai Indians cap.",
                            FranchiseId = 2,
                            ImageUrl = "/images/products/mi-cap.png",
                            IsActive = true,
                            Name = "MI Official Cap",
                            Price = 999.00m,
                            ProductType = 2,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official Royal Challengers Bengaluru jersey.",
                            FranchiseId = 3,
                            ImageUrl = "/images/products/rcb-jersey.png",
                            IsActive = true,
                            Name = "RCB Official Jersey",
                            Price = 2999.00m,
                            ProductType = 1,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official Royal Challengers Bengaluru cap.",
                            FranchiseId = 3,
                            ImageUrl = "/images/products/rcb-cap.png",
                            IsActive = true,
                            Name = "RCB Official Cap",
                            Price = 999.00m,
                            ProductType = 2,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official Kolkata Knight Riders jersey.",
                            FranchiseId = 4,
                            ImageUrl = "/images/products/kkr-jersey.png",
                            IsActive = true,
                            Name = "KKR Official Jersey",
                            Price = 2999.00m,
                            ProductType = 1,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official Sunrisers Hyderabad jersey.",
                            FranchiseId = 5,
                            ImageUrl = "/images/products/srh-jersey.png",
                            IsActive = true,
                            Name = "SRH Official Jersey",
                            Price = 2999.00m,
                            ProductType = 1,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Signed Chennai Super Kings photo.",
                            FranchiseId = 1,
                            ImageUrl = "/images/products/csk-signed-photo.png",
                            IsActive = true,
                            Name = "Autographed CSK Photo",
                            Price = 4999.00m,
                            ProductType = 4,
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("IPL.ECommerce.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPL.ECommerce.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("IPL.ECommerce.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPL.ECommerce.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("IPL.ECommerce.Domain.Entities.Franchise", "Franchise")
                        .WithMany("Products")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Franchise", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IPL.ECommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
